component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./build/.*
- ./build/classes/.*
- ./build/classes/org/.*
- ./build/classes/org/apache/.*
- ./build/classes/org/apache/hadoop/.*
- ./build/classes/org/apache/hadoop/classification/.*
- ./build/classes/org/apache/hadoop/conf/.*
- ./build/classes/org/apache/hadoop/filecache/.*
- ./build/classes/org/apache/hadoop/fs/.*
- ./build/classes/org/apache/hadoop/fs/ftp/.*
- ./build/classes/org/apache/hadoop/fs/kfs/.*
- ./build/classes/org/apache/hadoop/fs/permission/.*
- ./build/classes/org/apache/hadoop/fs/s3/.*
- ./build/classes/org/apache/hadoop/fs/s3native/.*
- ./build/classes/org/apache/hadoop/fs/shell/.*
- ./build/classes/org/apache/hadoop/hdfs/.*
- ./build/classes/org/apache/hadoop/hdfs/protocol/.*
- ./build/classes/org/apache/hadoop/hdfs/security/.*
- ./build/classes/org/apache/hadoop/hdfs/security/token/.*
- ./build/classes/org/apache/hadoop/hdfs/security/token/block/.*
- ./build/classes/org/apache/hadoop/hdfs/security/token/delegation/.*
- ./build/classes/org/apache/hadoop/hdfs/server/.*
- ./build/classes/org/apache/hadoop/hdfs/server/balancer/.*
- ./build/classes/org/apache/hadoop/hdfs/server/common/.*
- ./build/classes/org/apache/hadoop/hdfs/server/datanode/.*
- ./build/classes/org/apache/hadoop/hdfs/server/datanode/metrics/.*
- ./build/classes/org/apache/hadoop/hdfs/server/datanode/web/.*
- ./build/classes/org/apache/hadoop/hdfs/server/namenode/.*
- ./build/classes/org/apache/hadoop/hdfs/server/namenode/metrics/.*
- ./build/classes/org/apache/hadoop/hdfs/server/namenode/web/.*
- ./build/classes/org/apache/hadoop/hdfs/server/protocol/.*
- ./build/classes/org/apache/hadoop/hdfs/tools/.*
- ./build/classes/org/apache/hadoop/hdfs/util/.*
- ./build/classes/org/apache/hadoop/hdfs/web/.*
- ./build/classes/org/apache/hadoop/http/.*
- ./build/classes/org/apache/hadoop/http/lib/.*
- ./build/classes/org/apache/hadoop/io/.*
- ./build/classes/org/apache/hadoop/io/compress/.*
- ./build/classes/org/apache/hadoop/io/compress/bzip2/.*
- ./build/classes/org/apache/hadoop/io/compress/snappy/.*
- ./build/classes/org/apache/hadoop/io/compress/zlib/.*
- ./build/classes/org/apache/hadoop/io/file/.*
- ./build/classes/org/apache/hadoop/io/file/tfile/.*
- ./build/classes/org/apache/hadoop/io/nativeio/.*
- ./build/classes/org/apache/hadoop/io/retry/.*
- ./build/classes/org/apache/hadoop/io/serializer/.*
- ./build/classes/org/apache/hadoop/ipc/.*
- ./build/classes/org/apache/hadoop/ipc/metrics/.*
- ./build/classes/org/apache/hadoop/jmx/.*
- ./build/classes/org/apache/hadoop/log/.*
- ./build/classes/org/apache/hadoop/log/metrics/.*
- ./build/classes/org/apache/hadoop/mapred/.*
- ./build/classes/org/apache/hadoop/mapred/jobcontrol/.*
- ./build/classes/org/apache/hadoop/mapred/join/.*
- ./build/classes/org/apache/hadoop/mapred/lib/.*
- ./build/classes/org/apache/hadoop/mapred/lib/aggregate/.*
- ./build/classes/org/apache/hadoop/mapred/lib/db/.*
- ./build/classes/org/apache/hadoop/mapred/pipes/.*
- ./build/classes/org/apache/hadoop/mapred/tools/.*
- ./build/classes/org/apache/hadoop/mapreduce/.*
- ./build/classes/org/apache/hadoop/mapreduce/lib/.*
- ./build/classes/org/apache/hadoop/mapreduce/lib/db/.*
- ./build/classes/org/apache/hadoop/mapreduce/lib/fieldsel/.*
- ./build/classes/org/apache/hadoop/mapreduce/lib/input/.*
- ./build/classes/org/apache/hadoop/mapreduce/lib/jobcontrol/.*
- ./build/classes/org/apache/hadoop/mapreduce/lib/map/.*
- ./build/classes/org/apache/hadoop/mapreduce/lib/output/.*
- ./build/classes/org/apache/hadoop/mapreduce/lib/partition/.*
- ./build/classes/org/apache/hadoop/mapreduce/lib/reduce/.*
- ./build/classes/org/apache/hadoop/mapreduce/security/.*
- ./build/classes/org/apache/hadoop/mapreduce/security/token/.*
- ./build/classes/org/apache/hadoop/mapreduce/security/token/delegation/.*
- ./build/classes/org/apache/hadoop/mapreduce/server/.*
- ./build/classes/org/apache/hadoop/mapreduce/server/jobtracker/.*
- ./build/classes/org/apache/hadoop/mapreduce/server/tasktracker/.*
- ./build/classes/org/apache/hadoop/mapreduce/server/tasktracker/userlogs/.*
- ./build/classes/org/apache/hadoop/mapreduce/split/.*
- ./build/classes/org/apache/hadoop/metrics/.*
- ./build/classes/org/apache/hadoop/metrics/file/.*
- ./build/classes/org/apache/hadoop/metrics/ganglia/.*
- ./build/classes/org/apache/hadoop/metrics/jvm/.*
- ./build/classes/org/apache/hadoop/metrics/spi/.*
- ./build/classes/org/apache/hadoop/metrics/util/.*
- ./build/classes/org/apache/hadoop/metrics2/.*
- ./build/classes/org/apache/hadoop/metrics2/filter/.*
- ./build/classes/org/apache/hadoop/metrics2/impl/.*
- ./build/classes/org/apache/hadoop/metrics2/lib/.*
- ./build/classes/org/apache/hadoop/metrics2/sink/.*
- ./build/classes/org/apache/hadoop/metrics2/sink/ganglia/.*
- ./build/classes/org/apache/hadoop/metrics2/util/.*
- ./build/classes/org/apache/hadoop/net/.*
- ./build/classes/org/apache/hadoop/record/.*
- ./build/classes/org/apache/hadoop/record/compiler/.*
- ./build/classes/org/apache/hadoop/record/compiler/ant/.*
- ./build/classes/org/apache/hadoop/record/compiler/generated/.*
- ./build/classes/org/apache/hadoop/record/meta/.*
- ./build/classes/org/apache/hadoop/security/.*
- ./build/classes/org/apache/hadoop/security/authentication/.*
- ./build/classes/org/apache/hadoop/security/authentication/client/.*
- ./build/classes/org/apache/hadoop/security/authentication/server/.*
- ./build/classes/org/apache/hadoop/security/authentication/util/.*
- ./build/classes/org/apache/hadoop/security/authorize/.*
- ./build/classes/org/apache/hadoop/security/token/.*
- ./build/classes/org/apache/hadoop/security/token/delegation/.*
- ./build/classes/org/apache/hadoop/util/.*
- ./build/classes/org/apache/hadoop/util/bloom/.*
- ./build/classes/org/apache/hadoop/util/hash/.*
- ./build/ivy/.*
- ./build/ivy/lib/.*
- ./build/ivy/lib/Hadoop/.*
- ./build/ivy/lib/Hadoop/common/.*
- ./build/webapps/.*
- ./build/webapps/datanode/.*
- ./build/webapps/datanode/WEB-INF/.*
- ./build/webapps/hdfs/.*
- ./build/webapps/hdfs/WEB-INF/.*
- ./build/webapps/history/.*
- ./build/webapps/history/WEB-INF/.*
- ./build/webapps/job/.*
- ./build/webapps/job/WEB-INF/.*
- ./build/webapps/static/.*
- ./build/webapps/task/.*
- ./build/webapps/task/WEB-INF/.*
- ./c++/.*
- ./c++/Linux-amd64-64/.*
- ./c++/Linux-amd64-64/include/.*
- ./c++/Linux-amd64-64/include/hadoop/.*
- ./c++/Linux-amd64-64/lib/.*
- ./c++/Linux-i386-32/.*
- ./c++/Linux-i386-32/include/.*
- ./c++/Linux-i386-32/include/hadoop/.*
- ./c++/Linux-i386-32/lib/.*
- ./conf/.*
- ./contrib/.*
- ./contrib/datajoin/.*
- ./contrib/failmon/.*
- ./contrib/gridmix/.*
- ./contrib/hdfsproxy/.*
- ./contrib/hdfsproxy/bin/.*
- ./contrib/hdfsproxy/conf/.*
- ./contrib/hod/.*
- ./contrib/hod/bin/.*
- ./contrib/hod/conf/.*
- ./contrib/hod/hodlib/.*
- ./contrib/hod/hodlib/AllocationManagers/.*
- ./contrib/hod/hodlib/Common/.*
- ./contrib/hod/hodlib/GridServices/.*
- ./contrib/hod/hodlib/Hod/.*
- ./contrib/hod/hodlib/HodRing/.*
- ./contrib/hod/hodlib/NodePools/.*
- ./contrib/hod/hodlib/RingMaster/.*
- ./contrib/hod/hodlib/Schedulers/.*
- ./contrib/hod/hodlib/ServiceProxy/.*
- ./contrib/hod/hodlib/ServiceRegistry/.*
- ./contrib/hod/ivy/.*
- ./contrib/hod/support/.*
- ./contrib/hod/testing/.*
- ./contrib/index/.*
- ./contrib/streaming/.*
- ./contrib/vaidya/.*
- ./contrib/vaidya/bin/.*
- ./contrib/vaidya/conf/.*
- ./docs/.*
- ./docs/api/.*
- ./docs/api/org/.*
- ./docs/api/org/apache/.*
- ./docs/api/org/apache/hadoop/.*
- ./docs/api/org/apache/hadoop/class-use/.*
- ./docs/api/org/apache/hadoop/classification/.*
- ./docs/api/org/apache/hadoop/classification/class-use/.*
- ./docs/api/org/apache/hadoop/conf/.*
- ./docs/api/org/apache/hadoop/conf/class-use/.*
- ./docs/api/org/apache/hadoop/contrib/.*
- ./docs/api/org/apache/hadoop/contrib/failmon/.*
- ./docs/api/org/apache/hadoop/contrib/failmon/class-use/.*
- ./docs/api/org/apache/hadoop/contrib/index/.*
- ./docs/api/org/apache/hadoop/contrib/index/example/.*
- ./docs/api/org/apache/hadoop/contrib/index/example/class-use/.*
- ./docs/api/org/apache/hadoop/contrib/index/lucene/.*
- ./docs/api/org/apache/hadoop/contrib/index/lucene/class-use/.*
- ./docs/api/org/apache/hadoop/contrib/index/main/.*
- ./docs/api/org/apache/hadoop/contrib/index/main/class-use/.*
- ./docs/api/org/apache/hadoop/contrib/index/mapred/.*
- ./docs/api/org/apache/hadoop/contrib/index/mapred/class-use/.*
- ./docs/api/org/apache/hadoop/contrib/utils/.*
- ./docs/api/org/apache/hadoop/contrib/utils/join/.*
- ./docs/api/org/apache/hadoop/contrib/utils/join/class-use/.*
- ./docs/api/org/apache/hadoop/examples/.*
- ./docs/api/org/apache/hadoop/examples/class-use/.*
- ./docs/api/org/apache/hadoop/examples/dancing/.*
- ./docs/api/org/apache/hadoop/examples/dancing/class-use/.*
- ./docs/api/org/apache/hadoop/examples/terasort/.*
- ./docs/api/org/apache/hadoop/examples/terasort/class-use/.*
- ./docs/api/org/apache/hadoop/filecache/.*
- ./docs/api/org/apache/hadoop/filecache/class-use/.*
- ./docs/api/org/apache/hadoop/fs/.*
- ./docs/api/org/apache/hadoop/fs/class-use/.*
- ./docs/api/org/apache/hadoop/fs/ftp/.*
- ./docs/api/org/apache/hadoop/fs/ftp/class-use/.*
- ./docs/api/org/apache/hadoop/fs/kfs/.*
- ./docs/api/org/apache/hadoop/fs/kfs/class-use/.*
- ./docs/api/org/apache/hadoop/fs/permission/.*
- ./docs/api/org/apache/hadoop/fs/permission/class-use/.*
- ./docs/api/org/apache/hadoop/fs/s3/.*
- ./docs/api/org/apache/hadoop/fs/s3/class-use/.*
- ./docs/api/org/apache/hadoop/fs/s3native/.*
- ./docs/api/org/apache/hadoop/fs/s3native/class-use/.*
- ./docs/api/org/apache/hadoop/fs/shell/.*
- ./docs/api/org/apache/hadoop/fs/shell/class-use/.*
- ./docs/api/org/apache/hadoop/http/.*
- ./docs/api/org/apache/hadoop/http/class-use/.*
- ./docs/api/org/apache/hadoop/http/lib/.*
- ./docs/api/org/apache/hadoop/http/lib/class-use/.*
- ./docs/api/org/apache/hadoop/io/.*
- ./docs/api/org/apache/hadoop/io/class-use/.*
- ./docs/api/org/apache/hadoop/io/compress/.*
- ./docs/api/org/apache/hadoop/io/compress/bzip2/.*
- ./docs/api/org/apache/hadoop/io/compress/bzip2/class-use/.*
- ./docs/api/org/apache/hadoop/io/compress/class-use/.*
- ./docs/api/org/apache/hadoop/io/compress/snappy/.*
- ./docs/api/org/apache/hadoop/io/compress/snappy/class-use/.*
- ./docs/api/org/apache/hadoop/io/compress/zlib/.*
- ./docs/api/org/apache/hadoop/io/compress/zlib/class-use/.*
- ./docs/api/org/apache/hadoop/io/file/.*
- ./docs/api/org/apache/hadoop/io/file/tfile/.*
- ./docs/api/org/apache/hadoop/io/file/tfile/class-use/.*
- ./docs/api/org/apache/hadoop/io/nativeio/.*
- ./docs/api/org/apache/hadoop/io/nativeio/class-use/.*
- ./docs/api/org/apache/hadoop/io/retry/.*
- ./docs/api/org/apache/hadoop/io/retry/class-use/.*
- ./docs/api/org/apache/hadoop/io/serializer/.*
- ./docs/api/org/apache/hadoop/io/serializer/class-use/.*
- ./docs/api/org/apache/hadoop/ipc/.*
- ./docs/api/org/apache/hadoop/ipc/class-use/.*
- ./docs/api/org/apache/hadoop/ipc/metrics/.*
- ./docs/api/org/apache/hadoop/ipc/metrics/class-use/.*
- ./docs/api/org/apache/hadoop/jmx/.*
- ./docs/api/org/apache/hadoop/jmx/class-use/.*
- ./docs/api/org/apache/hadoop/log/.*
- ./docs/api/org/apache/hadoop/log/class-use/.*
- ./docs/api/org/apache/hadoop/log/metrics/.*
- ./docs/api/org/apache/hadoop/log/metrics/class-use/.*
- ./docs/api/org/apache/hadoop/mapred/.*
- ./docs/api/org/apache/hadoop/mapred/class-use/.*
- ./docs/api/org/apache/hadoop/mapred/jobcontrol/.*
- ./docs/api/org/apache/hadoop/mapred/jobcontrol/class-use/.*
- ./docs/api/org/apache/hadoop/mapred/join/.*
- ./docs/api/org/apache/hadoop/mapred/join/class-use/.*
- ./docs/api/org/apache/hadoop/mapred/lib/.*
- ./docs/api/org/apache/hadoop/mapred/lib/aggregate/.*
- ./docs/api/org/apache/hadoop/mapred/lib/aggregate/class-use/.*
- ./docs/api/org/apache/hadoop/mapred/lib/class-use/.*
- ./docs/api/org/apache/hadoop/mapred/lib/db/.*
- ./docs/api/org/apache/hadoop/mapred/lib/db/class-use/.*
- ./docs/api/org/apache/hadoop/mapred/pipes/.*
- ./docs/api/org/apache/hadoop/mapred/pipes/class-use/.*
- ./docs/api/org/apache/hadoop/mapred/tools/.*
- ./docs/api/org/apache/hadoop/mapred/tools/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/.*
- ./docs/api/org/apache/hadoop/mapreduce/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/db/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/db/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/fieldsel/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/fieldsel/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/input/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/input/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/jobcontrol/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/jobcontrol/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/map/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/map/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/output/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/output/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/partition/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/partition/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/reduce/.*
- ./docs/api/org/apache/hadoop/mapreduce/lib/reduce/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/security/.*
- ./docs/api/org/apache/hadoop/mapreduce/security/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/security/token/.*
- ./docs/api/org/apache/hadoop/mapreduce/security/token/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/security/token/delegation/.*
- ./docs/api/org/apache/hadoop/mapreduce/security/token/delegation/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/server/.*
- ./docs/api/org/apache/hadoop/mapreduce/server/jobtracker/.*
- ./docs/api/org/apache/hadoop/mapreduce/server/jobtracker/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/server/tasktracker/.*
- ./docs/api/org/apache/hadoop/mapreduce/server/tasktracker/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/server/tasktracker/userlogs/.*
- ./docs/api/org/apache/hadoop/mapreduce/server/tasktracker/userlogs/class-use/.*
- ./docs/api/org/apache/hadoop/mapreduce/split/.*
- ./docs/api/org/apache/hadoop/mapreduce/split/class-use/.*
- ./docs/api/org/apache/hadoop/metrics/.*
- ./docs/api/org/apache/hadoop/metrics/class-use/.*
- ./docs/api/org/apache/hadoop/metrics/file/.*
- ./docs/api/org/apache/hadoop/metrics/file/class-use/.*
- ./docs/api/org/apache/hadoop/metrics/ganglia/.*
- ./docs/api/org/apache/hadoop/metrics/ganglia/class-use/.*
- ./docs/api/org/apache/hadoop/metrics/jvm/.*
- ./docs/api/org/apache/hadoop/metrics/jvm/class-use/.*
- ./docs/api/org/apache/hadoop/metrics/spi/.*
- ./docs/api/org/apache/hadoop/metrics/spi/class-use/.*
- ./docs/api/org/apache/hadoop/metrics/util/.*
- ./docs/api/org/apache/hadoop/metrics/util/class-use/.*
- ./docs/api/org/apache/hadoop/metrics2/.*
- ./docs/api/org/apache/hadoop/metrics2/class-use/.*
- ./docs/api/org/apache/hadoop/metrics2/filter/.*
- ./docs/api/org/apache/hadoop/metrics2/filter/class-use/.*
- ./docs/api/org/apache/hadoop/metrics2/impl/.*
- ./docs/api/org/apache/hadoop/metrics2/impl/class-use/.*
- ./docs/api/org/apache/hadoop/metrics2/lib/.*
- ./docs/api/org/apache/hadoop/metrics2/lib/class-use/.*
- ./docs/api/org/apache/hadoop/metrics2/sink/.*
- ./docs/api/org/apache/hadoop/metrics2/sink/class-use/.*
- ./docs/api/org/apache/hadoop/metrics2/sink/ganglia/.*
- ./docs/api/org/apache/hadoop/metrics2/sink/ganglia/class-use/.*
- ./docs/api/org/apache/hadoop/metrics2/util/.*
- ./docs/api/org/apache/hadoop/metrics2/util/class-use/.*
- ./docs/api/org/apache/hadoop/net/.*
- ./docs/api/org/apache/hadoop/net/class-use/.*
- ./docs/api/org/apache/hadoop/record/.*
- ./docs/api/org/apache/hadoop/record/class-use/.*
- ./docs/api/org/apache/hadoop/record/compiler/.*
- ./docs/api/org/apache/hadoop/record/compiler/ant/.*
- ./docs/api/org/apache/hadoop/record/compiler/ant/class-use/.*
- ./docs/api/org/apache/hadoop/record/compiler/class-use/.*
- ./docs/api/org/apache/hadoop/record/compiler/generated/.*
- ./docs/api/org/apache/hadoop/record/compiler/generated/class-use/.*
- ./docs/api/org/apache/hadoop/record/meta/.*
- ./docs/api/org/apache/hadoop/record/meta/class-use/.*
- ./docs/api/org/apache/hadoop/security/.*
- ./docs/api/org/apache/hadoop/security/authentication/.*
- ./docs/api/org/apache/hadoop/security/authentication/client/.*
- ./docs/api/org/apache/hadoop/security/authentication/client/class-use/.*
- ./docs/api/org/apache/hadoop/security/authentication/server/.*
- ./docs/api/org/apache/hadoop/security/authentication/server/class-use/.*
- ./docs/api/org/apache/hadoop/security/authentication/util/.*
- ./docs/api/org/apache/hadoop/security/authentication/util/class-use/.*
- ./docs/api/org/apache/hadoop/security/authorize/.*
- ./docs/api/org/apache/hadoop/security/authorize/class-use/.*
- ./docs/api/org/apache/hadoop/security/class-use/.*
- ./docs/api/org/apache/hadoop/security/token/.*
- ./docs/api/org/apache/hadoop/security/token/class-use/.*
- ./docs/api/org/apache/hadoop/security/token/delegation/.*
- ./docs/api/org/apache/hadoop/security/token/delegation/class-use/.*
- ./docs/api/org/apache/hadoop/streaming/.*
- ./docs/api/org/apache/hadoop/streaming/class-use/.*
- ./docs/api/org/apache/hadoop/streaming/io/.*
- ./docs/api/org/apache/hadoop/streaming/io/class-use/.*
- ./docs/api/org/apache/hadoop/typedbytes/.*
- ./docs/api/org/apache/hadoop/typedbytes/class-use/.*
- ./docs/api/org/apache/hadoop/util/.*
- ./docs/api/org/apache/hadoop/util/bloom/.*
- ./docs/api/org/apache/hadoop/util/bloom/class-use/.*
- ./docs/api/org/apache/hadoop/util/class-use/.*
- ./docs/api/org/apache/hadoop/util/hash/.*
- ./docs/api/org/apache/hadoop/util/hash/class-use/.*
- ./docs/images/.*
- ./docs/jdiff/.*
- ./docs/jdiff/changes/.*
- ./docs/skin/.*
- ./docs/skin/images/.*
- ./ivy/.*
- ./lib/.*
- ./lib/jdiff/.*
- ./lib/jsp-2.1/.*
- ./lib/native/.*
- ./lib/native/Linux-amd64-64/.*
- ./lib/native/Linux-i386-32/.*
- ./libexec/.*
- ./ourlib/.*
- ./sbin/.*
- ./share/.*
- ./share/hadoop/.*
- ./share/hadoop/templates/.*
- ./share/hadoop/templates/conf/.*
- ./webapps/.*
- ./webapps/datanode/.*
- ./webapps/datanode/WEB-INF/.*
- ./webapps/hdfs/.*
- ./webapps/hdfs/WEB-INF/.*
- ./webapps/history/.*
- ./webapps/history/WEB-INF/.*
- ./webapps/job/.*
- ./webapps/job/WEB-INF/.*
- ./webapps/static/.*
- ./webapps/task/.*
- ./webapps/task/WEB-INF/.*
